### PR TITLE
Extra Info

### PR DESCRIPTION
**Pull request by wbyoko**
same as last pull request with contextual class added to conversation icon.

### CODE REVIEW

**Comment by mfkp** [comment]
A few things:

- "Display Extra Info/Hide Extra Info" in options - should describe what "extra info" is
- The console.logs on 138 & 139 of controls.js should be removed, but also, they're getting called a ton on my system.
  - see this gist for the log: https://gist.github.com/mfkp/2ab4a9aada59248ecbbe (these messages repeat every 4 seconds)
- The "extra info" only displays on one row out of all of my matches, is this correct? should it be missing rows?

Example:

example

**Comment by wbyoko** [comment]
The initial sync isn't immediate. 

I made a queue and even with max two concurrent request the api starts returning null.

I reversed it so most recent matches were synced first, instead of the last.  

I'll switch it to a 'lastActive' sort.

**Comment by wbyoko** [comment]
The queue is building, one of the requests is failing which will dissolve the remaining request queue.

The tinder api is sensitive to multiple requests so maybe chain may need be to paused by a couple milliseconds if your internet is fast.

**Comment by wbyoko** [comment]
You may want to try to debug this a little bit.

1. Try Clicking into a profile and then the Conversation Summary should be filled. If that works the API.userInfo decorator is working.

2. added a $timeout(noop, 100).then... to every addition infoQueue. we may need to generally debounce the queue api calls

**Comment by mfkp** [comment]
Did a bit of debugging and found out my problem was from old spam accounts that were deleted and causing problems. Added a little extra safety in checking convos here: 6ae40b9044aba2bf8f6f44dacb5a4dfc28168b30

Seems to be working correctly now.

**Pull request merged**
